export const data = [
  {
    id: '1', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/1.jpg', description: 'Broccoli stir fry',
    ingredients: ['1/2 pounds (2 large heads) broccoli', '1 head broccolini (or 1 additional head of broccoli)', '1 medium red onion', '1 orange bell pepper', '2 portobello mushroom caps', '3 garlic cloves', '2 teaspoons ginger, grated (about a 2-inch nub)', '2 tablespoons mirin', '2 tablespoons  vinegar', '2 tablespoons soy sauce', '1 teaspoon Sriracha hot sauce', '2 tablespoons sesame oil (regular, not toasted)'],
    instructions: ['Chop the broccoli and broccolini into large florets (about 6 cups florets total). Chop the red onion into bite sized squares. Dice the pepper into bite sized squares', 'Remove the stems from the portobellos (if necessary), slice them into strips, then cut the larger pieces in half. Place all of the vegetables in a large bowl', 'Mince the garlic. Peel the ginger and grate it. Place them together in a small bowl.', 'Stir together the mirin, rice vinegar, soy sauce, and Sriracha in a small bowl.', 'In a large skillet over high heat, and heat the oil. Add the broccoli, broccolini (if using), red onion, bell pepper, and mushrooms and cook 6 to 7 minutes until just starting to brown on edges, stirring occasionally.', 'Add the garlic and ginger cook for 1 minute more, until broccoli is crisp tender but still bright green.', 'Turn off the heat and add the sauce, stirring until combined. Taste and add additional pinches salt as necessary. Serve immediately. Garnish with sesame seeds and green onion (optional).'],
    ratings: [],
    dietaryRestrictions: ['vegetarian'],
    difficultyLevel: 'intermediate',
    nutrition: {
      totalCalories: 370,
      proteinPercentage: 41,
      carbsPercentage: 52,
      fatPercentage: 7,
    },
    serving: 5,
    time: 15
  },
  {
    id: '2', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/2.jpg',
    description: 'Flower Power Eggs',
    ingredients: [' bell pepper', '1 tbsp. vegetable oil', '4 large eggs', 'Chopped parsley, for garnish'],
    instructions: ['Slice bell pepper (or 4 in different colors) horizontally to make four 1/2-inch-thick rings and remove inner white flesh and seeds.', 'In 12-inch nonstick skillet, heat vegetable oil on medium. Cook peppers 2 minutes. Turn peppers over; crack 1 egg into center of each ring. Cook, covered, until eggs have reached desired doneness. Season with 1/4 teaspoon each salt and pepper.', 'To serve, garnish with chopped parsle'],
    ratings: [],
    dietaryRestrictions: ['vegetarian', 'vegan'],
    difficultyLevel: 'beginner',
    nutrition: {
      totalCalories: 220,
      proteinPercentage: 41,
      carbsPercentage: 52,
      fatPercentage: 7,
    },
    serving: 5,
    time: 25
  },
  // {
  //   id: '3',
  //   imageSource: 'https://storage.googleapis.com/makeiteasyrp808/3.jpg',
  //   description: 'Chicken fried rice',
  //   ingredients: ['2 tablespoons sesame oil',
  //     '2 tablespoons canola or vegetable oil', '3/4 to 1 pound boneless skinless chicken breasts', 'diced into 1/2-inch pieces', '1/2 cups frozen peas and diced carrots blend ', '3 green onions, trimmed and sliced into thin rounds', ' 2 to 3 garlic cloves, finely minced', '3 large eggs, lightly beaten', '4 cups cooked rice (I use white, long-grain or brown may be substituted. To save time use two 8.8-ounce pouches cooked and ready-to-serve rice)', '3 to 4 tablespoons low-sodium soy sauce',
  //     'salt and pepper, optional and to taste',],
  //   instructions: ['To a large non-stick skillet or wok, add the oils, chicken, and cook over medium-high heat for about 3 to 5 minutes, flipping intermittently so all sides cook evenly.', ' Cooking time will vary based on thickness of chicken breasts and sizes of pieces.', 'Remove chicken with a slotted spoon (allow oils and cooking juices from chicken to remain in skillet) and place chicken on a plate; set aside.', 'Add the peas, carrots, green onions, and cook for about 2 minutes, or until vegetables begin to soften, stir intermittently.', 'Add the garlic and cook for 1 minute, stir intermittently.', 'Push vegetables to one side of the skillet, add the eggs to the other side, and cook to scramble, stirring as necessary.'],
  //   ratings: [],
  //   dietaryRestrictions: ['non-vegetarian'],
  //   difficultyLevel: 'advanced',
  //   nutrition: {
  //     totalCalories: 870,
  //     proteinPercentage: 41,
  //     carbsPercentage: 52,
  //     fatPercentage: 7,
  //   },
  //   serving: 5,
  //   time: 55
  // },
  {
    id: '4', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/4.jpg',
    description: 'Sushi',
    ingredients: ['6 sheets sushi seaweed aka nori', '1 batch prepared sushi rice', '1/2 lb sashimi-grade raw salmon or desired raw fish of choice', '4 oz cream cheese sliced into strips', '1 avocado sliced', 'soy sauce for serving'],
    instructions: ['Smooth gently with a rice paddle.', 'Layer salmon, cream cheese, and avocado on the rice, and roll it up tightly.', 'Slice with a sharp knife, and enjoy right away with soy sauce.'],
    ratings: [],
    dietaryRestrictions: ['non'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 670,
      proteinPercentage: 41,
      carbsPercentage: 52,
      fatPercentage: 7,
    },
    serving: 5,
    time: 40
  },
  {
    id: '5',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/5.jpg',
    description: 'Chicken Parmesan',
    ingredients: ['3 boneless skinless chicken breasts, cut in half horizontally to make 6 breast halves*', '½ cup freshly grated parmesan cheese, divided', '2 eggs', '1 cup panko bread crumbs', '1 cup Italian style bread crumbs, or panko', '1 teaspoon garlic powder', '3 Tablespoons oil', '24 ounces marinara sauce, or HOMEMADE', '1 cup shredded mozzarella cheese', 'fresh basil leaves, for serving'],
    instructions: ['Preheat oven to 450 degrees F.',
      'Butterfly chicken breasts: Place one hand on top of the breast and carefully run a knife through the center of the meat to create two, even, thin breast halves.',
      'Pat chicken dry and season well on both sides with salt and pepper.',
      'Add eggs to a shallow bowl and beat well. Add breadcrumbs, parmesan and garlic powder to another shallow bowl and stir to combine.',
      'Dip each piece of chicken into the egg mixture, and then press into breadcrumbs, coating on both sides.',
      'Add oil to a large skillet over medium-high heat. Once hot, add breaded chicken and cook for about 2 minutes on each side, until golden, but not cooked through.',
      ' to cover the bottom of the pan. Place breaded chicken on top.',
      'Add a spoonful of marinara sauce over the chicken, followed by a sprinkle of mozzarella and parmesan cheese.',
      'Bake for 10-15 minutes or until cheese is melted and bubbly and chicken is cooked through (165 degrees F).',
      'Garnish with fresh chopped basil. Serve over hot cooked spaghetti noodles, with extra sauce, if desired.'],
    ratings: [],
    dietaryRestrictions: ['non'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 378,
      proteinPercentage: 41,
      carbsPercentage: 52,
      fatPercentage: 7,
    },
    serving: 6,
    time: 35
  },

  {
    id: '6',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/6.jpg',
    description: 'Taco salad',
    ingredients: ['1 pound lean ground beef',
      '1 (16 ounce) can chili beans',
      '1 (16 ounce) bottle French dressing',
      '1 (1.25 ounce) package taco seasoning mix',
      '1 (14.5 ounce) package tortilla chips',
      '1 head iceberg lettuce, shredded',
      '2 cups shredded Cheddar cheese',
      '1 cup chopped tomatoes',
      '½ cup prepared salsa',
      '4 tablespoons sour cream'],
    instructions:
      ['Heat a large skillet over medium-high heat.',
        'Cook and stir ground beef in the hot skillet until browned and crumbly, 5 to 7 minutes.',
        'Drain and discard grease. Stir in chili beans, French-style dressing, and seasoning mix.',
        'Fill the empty dressing bottle 2/3 full of water and add to the skillet.',
        'Bring to a boil, reduce heat, and simmer for 15 minutes.',
        'Crush the bag of chips, open the bag, and toss crushed chips into a large bowl. Add lettuce, cheese, and tomatoes.',
        'Pour meat mixture into the bowl; mix well. Top with salsa and sour cream.'],
    ratings: [],
    dietaryRestrictions: ['non'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 846,
      proteinPercentage: 24.42,
      carbsPercentage: 21.19,
      fatPercentage: 54.89,
    },
    serving: 8,
    time: 35
  },
  {
    id: '7',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/7a.jpg',
    description: 'Grilled Shrimp',
    ingredients:
      ['1 large clove garlic',
        '1 teaspoon coarse salt',
        '1 teaspoon paprika',
        '½ teaspoon cayenne pepper',
        '2 tablespoons olive oil',
        '2 teaspoons lemon juice',
        '2 pounds large shrimp, peeled and deveined',
        '8 wedges lemon, for garnish'],
    instructions: ['Preheat a grill for medium heat.',
      'Crush garlic and salt together in a small bowl with a fork. Mix in paprika and cayenne. Stir in olive oil and lemon juice to form a paste.',
      'Combine garlic paste and shrimp in a large bowl and toss until shrimp are evenly coated.',
      'Lightly oil the grill grate. Grill shrimp until opaque, 2 to 3 minutes.'],
    ratings: [],
    dietaryRestrictions: ['non'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 164,
      proteinPercentage: 60.98,
      carbsPercentage: 13.29,
      fatPercentage: 25.73,
    },
    serving: 6,
    time: 25
  },
  {
    id: '8',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/8.jpg',
    description: 'Creamy Pasta',
    ingredients: ['1 tablespoon panko bread crumbs',
      '1 tablespoon hemp seeds',
      '1/3 teaspoon sea salt',
      'extra-virgin olive oil to taste, for drizzling',
      '1/4 cup chopped fresh herbs (chives, tarragon, or parsley)',
      '10 ounces shell pasta',
      '1 tablespoon extra-virgin olive oil',
      '3 cups Brussels sprouts, halved',
      '2 tablespoons white wine (or water)',
      '2 scallions, sliced',
      'sea salt and freshly ground black pepper to taste',
      '1 cup Almond Breeze Unsweetened Original Almondmilk or Almond Breeze Extra Creamy Almondmilk',
      '1 cup raw slivered almonds',
      '2 tablespoons white miso paste',
      '2 garlic cloves',
      '1/2 teaspoon Dijon mustard',
      '1/4 cup freshly squeezed lemon juice',
      '2 tablespoons extra-virgin olive oil',
      '1/2 teaspoon sea salt'],
    instructions:
      ['Preheat the oven to 400 degrees F (200 degrees c) and brush a 7x9 baking dish with olive oil.',
        'Make the White Miso Sauce: In a high-speed blender, puree the cashews, miso paste, garlic, Dijon mustard, water, lemon juice, olive oil, and salt until smooth.',
        'Make the pasta: Bring a large pot of salted water to a boil. Prepare the pasta according to the instructions on the package, cooking until al dente. Drain and toss with a little olive oil so that it doesn’t get clumpy.',
        'Heat 1 tablespoon olive oil in a medium skillet over medium-high heat. Add Brussels sprouts and cook, stirring occasionally until browned and beginning to soften, 5 to 7 minutes. Remove from heat, pour in white wine (or water). Stir to scrape up any bits that have stuck to the bottom of the pan.',
        'Add pasta, scallions, and white miso sauce. Stir to coat, then transfer to the baking dish. Top with panko bread crumbs, hemp seeds, a few pinches of salt, and drizzle the top with olive oil.',
        'Bake, covered, until the Brussels sprouts are fully tender and the dish is warmed through, about 15 minutes.',
        'Remove from the oven, top with fresh herbs and serve.'],
    ratings: [],
    dietaryRestrictions: ['vegan'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 385,
      proteinPercentage: 72.73,
      carbsPercentage: 8.31,
      fatPercentage: 21.95,
    },
    serving: 5,
    time: 45
  },
  {
    id: '9',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/9.jpg',
    description: 'Sushi',
    ingredients: ['1 ½ cups uncooked short-grain white rice',
      '1 ½ cups water',
      '⅓ cup red wine vinegar',
      '2 teaspoons white sugar',
      '1 teaspoon salt',
      '½ avocado - peeled, pitted, and thinly sliced',
      '1 teaspoon lemon juice',
      '¼ cup sesame seeds, or as needed',
      '½ cucumber - peeled, seeded, and cut into matchsticks',
      '½ green bell pepper, seeded and cut into matchsticks',
      '½ zucchini, cut into matchsticks'],
    instructions:
      ['Place rice and water in a saucepan over high heat, bring to a boil, and reduce heat to very low.',
        'Cover with a tight-fitting lid and simmer rice until water is absorbed, about 15 minutes. Remove rice from heat and allow to stand covered for 10 minutes.',
        'Mix red wine vinegar, sugar, and salt in a bowl until sugar has dissolved. Fluff rice with a fork and transfer into a large bowl; pour vinegar mixture into the rice and stir to coat rice.',
        'Spread rice out onto a large piece of parchment paper and fan the rice until cool. Cover rice with damp paper towels.',
        'Sprinkle avocado slices with lemon juice in a bowl.',
        'Spread a thin layer of sesame seeds onto a sushi mat. Pick up about half a cup of cooled rice and place onto sushi mat in an even layer. Place 1/4 of the cucumber, avocado slices, bell pepper, and zucchini in a line down the middle of the rice.',
        'Pick up the edge of the sushi mat, fold the bottom edge of the sheet up, enclosing the filling, and tightly roll the sushi into a thick cylinder.',
        'Once the sushi is rolled, wrap it in the mat and gently squeeze to compact it tightly.',
        'Repeat with remaining ingredients to make 4 rolls. Place rolls on a serving plate, slice into 6 or 8 pieces per roll, and cover with damp paper towels until serving time.'],
    ratings: [],
    dietaryRestrictions: ['vegetarian'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 670,
      proteinPercentage: 41,
      carbsPercentage: 52,
      fatPercentage: 7,
    },
    serving: 4,
    time: 55
  },
  {
    id: '10',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/10.jpg',
    description: 'Roasted Chicken',
    ingredients:
      ['2 pounds red potatoes (about 6 medium), cut into 3/4-inch pieces',
        '1 large onion, coarsely chopped',
        '2 tablespoons olive oil',
        '3 garlic cloves, minced',
        '1-1/4 teaspoons salt, divided',
        '1 tablespoon minced fresh rosemary or 1 teaspoon dried rosemary, crushed, divided',
        '3/4 teaspoon pepper, divided',
        '1/2 teaspoon paprika',
        '6 bone-in chicken thighs (about 2-1/4 pounds), skin removed',
        '6 cups fresh baby spinach (about 6 ounces)',
        'Lemon wedges, optional'],
    instructions: ['Preheat oven to 425°. In a large bowl, combine potatoes, onion, oil, garlic, 3/4 teaspoon salt, 2 teaspoons fresh rosemary or 1/2 teaspoon dried rosemary, and 1/2 teaspoon pepper; toss to coat.',
      'Transfer to a 15x10x1-in. baking pan coated with cooking spray.',
      'In a small bowl, mix paprika and the remaining salt, rosemary, and pepper. Sprinkle chicken with paprika mixture; arrange over vegetables.',
      'Roast until a thermometer inserted in chicken reads 170°-175° and vegetables are just tender, 35-40 minutes.',
      'Remove chicken to a serving platter; keep warm.',
      'Top vegetables with spinach.',
      'Roast until vegetables are tender and spinach is wilted, 8-10 minutes longer.',
      'Stir vegetables to combine; serve with chicken. If desired, serve with additional fresh rosemary and lemon wedges.'],
    ratings: [],
    dietaryRestrictions: ['gluten-free'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 357,
      proteinPercentage: 41,
      carbsPercentage: 52,
      fatPercentage: 7,
    },
    serving: 3,
    time: 35
  },

  {
    id: '12',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/12.jpg',
    description: ' Korma',
    ingredients:
      ['1 red onion, quartered, divided',
        '1 green  chile pepper, stemmed',
        '½ cup water, divided',
        '¼ cup raw cashews',
        '2 cloves garlic',
        '2 tablespoons tomato paste',
        '1 (1 inch) piece fresh ginger',
        '5 whole cloves',
        '3 green cardamom pods',
        '1 black cardamom pod',
        '1 bay leaf',
        '1 teaspoon cumin seeds',
        '¼ teaspoon whole black peppercorns',
        '¼ teaspoon ground coriander',
        '¼ inch cinnamon stick',
        '¼ cup light vegetable oil',
        '8 ¾ ounces cauliflower, cut into large pieces',
        '5 ¼ ounces broccoli, cut into large pieces',
        '2 tomatoes, cut into large chunks',
        '1 cup canned chickpeas (garbanzo beans), drained with liquid reserved',
        '1 carrot, sliced',
        '1 red eye chile pepper, chopped',
        '½ tablespoon garam masala',
        '½ teaspoon ground turmeric',
        '¼ teaspoon chili powder',
        '1 cup baby spinach leaves',
        '1 cup full-fat coconut milk',
        '½ cup vegan yogurt',
        '2 ounces roasted cashews, chopped',
        '½ cup chopped fresh cilantro'],
    instructions: ['Blend 1/4 of the onion, green chile pepper, 1/4 cup water, cashews, garlic, tomato paste, and ginger together in an electric blender, adding extra water if necessary, until paste is creamy and has the consistency of a pesto. Set aside.',
      'Combine cloves, green and black cardamom pods, bay leaf, cumin seeds, peppercorns, coriander, and cinnamon in a mortar. Smash using a pestle to break open spices slightly, 3 to 4 times. Thinly slice remaining onion quarters.',
      'Turn on a multi-functional pressure cooker (such as Instant Pot®) and select Saute function. Add smashed spice mixture and toast until fragrant, about 30 seconds. Pour in oil followed by cashew pesto, onion slices, cauliflower, broccoli, tomatoes, chickpeas, carrot, red chile pepper, garam masala, turmeric, and chili powder. Stir. Cancel the Saute function. Close and lock the lid.',
      'Select high pressure according to manufacturers instructions; set timer for 5 minutes. Allow 10 minutes for pressure to build.',
      'Release pressure using the natural-release method according to manufacturers instructions, 10 to 40 minutes. Unlock and remove the lid. Stir in spinach and mix to help wilt. Stir in coconut milk and yogurt. Mix and serve with roasted cashews and cilantro on top.'],
    ratings: [],
    dietaryRestrictions: ['gluten-free'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 544,
      proteinPercentage: 32.85,
      carbsPercentage: 9.56,
      fatPercentage: 64.34,
    },
    serving: 4,
    time: 55
  },
  {
    id: '13',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/13.jpg',
    description: ' Greek Couscous Salad',
    ingredients:
      ['½ cup water',
        '¼ cup chicken broth',
        '1 teaspoon minced garlic',
        '½ cup pearl (Israeli) couscous',
        '1 cup canned chickpeas (garbanzo beans), rinsed and drained',
        '¼ cup chopped sun-dried tomatoes',
        '¼ cup sliced Kalamata olives',
        '2 tablespoons crumbled feta cheese',
        '1 tablespoon white wine vinegar',
        '1 ½ teaspoons lemon juice',
        '1 teaspoon dried oregano',
        '½ teaspoon ground black pepper'],
    instructions: ['Pour water and chicken broth into a saucepan; stir in the garlic and bring to a boil. Stir in pearl couscous, cover the pan, and remove from heat. Allow couscous to stand until water has been absorbed, about 5 minutes; fluff with a fork. Allow couscous to cool to warm temperature.',
      'Lightly toss couscous, chickpeas, sun-dried tomatoes, olives, and feta cheese in a large serving bowl.',
      'To make the dressing: Mix white wine vinegar, lemon juice, oregano, and black pepper in a small bowl until well combined. Pour over couscous mixture; toss again to serve.'],
    ratings: [],
    dietaryRestrictions: ['vegetarian'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 254,
      proteinPercentage: 14.17,
      carbsPercentage: 66.14,
      fatPercentage: 21.26,
    },
    serving: 3,
    time: 45
  },
  {
    id: '14',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/14.jpg',
    description: ' Bibimbap',
    ingredients:
      ['1 English cucumber, cut into matchsticks',
        '¼ cup gochujang (Korean hot pepper paste) (Optional)',
        '1 bunch fresh spinach, cut into thin strips',
        '1 tablespoon soy sauce',
        '2 teaspoons olive oil, divided',
        '2 carrots, cut into matchsticks',
        '1 clove garlic, minced',
        '1 pinch red pepper flakes',
        '1 pound thinly-sliced beef top round steak',
        '4 large eggs',
        '4 cups cooked white rice',
        '4 teaspoons toasted sesame oil, divided',
        '1 teaspoon sesame seeds',
        '2 teaspoons gochujang (Korean hot pepper paste), divided (Optional)'],
    instructions: ['Stir together cucumber pieces and gochujang paste in a bowl; set aside.',
      'Bring about 2 cups water to a boil in a large nonstick skillet and stir in spinach; cook until bright green and wilted, 2 to 3 minutes.',
      'Drain spinach and squeeze out as much moisture as possible; set spinach aside in a bowl and stir in soy sauce.',
      'Heat 1 teaspoon olive oil in a large nonstick skillet; cook and stir carrots until softened, about 3 minutes.',
      'Stir in garlic and cook just until fragrant, about 1 minute. Stir in cucumber mixture; sprinkle with red pepper flakes. Set carrot mixture aside in a bowl.',
      'Brown beef in a clean nonstick skillet over medium heat, about 5 minutes per side; set aside.',
      'Heat remaining 1 teaspoon olive oil in another nonstick skillet over medium-low heat.',
      'Fry eggs just on one side until yolks are runny, but whites are firm, 2 to 4 minutes.',
      'Divide cooked rice into 4 large serving bowls; top with spinach mixture, a few pieces of beef, and cucumber mixture. Place 1 egg atop each serving.',
      'Drizzle each bowl with 1 teaspoon sesame oil, a sprinkle of sesame seeds, and a small amount of gochujang paste if desired.'],
    ratings: [],
    dietaryRestrictions: ['non'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 569,
      proteinPercentage: 24.69,
      carbsPercentage: 44.18,
      fatPercentage: 30.13,
    },
    serving: 4,
    time: 35
  },
  {
    id: '3',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/3.jpg',
    description: 'Chicken fried rice',
    ingredients: ['2 tablespoons sesame oil',
      '2 tablespoons canola or vegetable oil', '3/4 to 1 pound boneless skinless chicken breasts', 'diced into 1/2-inch pieces', '1/2 cups frozen peas and diced carrots blend ', '3 green onions, trimmed and sliced into thin rounds', ' 2 to 3 garlic cloves, finely minced', '3 large eggs, lightly beaten', '4 cups cooked rice (I use white, long-grain or brown may be substituted. To save time use two 8.8-ounce pouches cooked and ready-to-serve rice)', '3 to 4 tablespoons low-sodium soy sauce',
      'salt and pepper, optional and to taste',],
    instructions: ['To a large non-stick skillet or wok, add the oils, chicken, and cook over medium-high heat for about 3 to 5 minutes, flipping intermittently so all sides cook evenly.', ' Cooking time will vary based on thickness of chicken breasts and sizes of pieces.', 'Remove chicken with a slotted spoon (allow oils and cooking juices from chicken to remain in skillet) and place chicken on a plate; set aside.', 'Add the peas, carrots, green onions, and cook for about 2 minutes, or until vegetables begin to soften, stir intermittently.', 'Add the garlic and cook for 1 minute, stir intermittently.', 'Push vegetables to one side of the skillet, add the eggs to the other side, and cook to scramble, stirring as necessary.'],
    ratings: [],
    dietaryRestrictions: ['non'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 870,
      proteinPercentage: 41,
      carbsPercentage: 52,
      fatPercentage: 7,
    },
    serving: 5,
    time: 55
  },
  {
    id: '15',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/11a.jpg',
    description: ' Jambalaya',
    ingredients:
      ['boneless chicken breasts and/or thighs',
        'andouille sausage',
        'tomato paste',
        'white onion',
        'celery',
        'green bell pepper',
        'garlic',
        'chicken broth',
        'diced tomatoes',
        'dried oregano',
        'bay leaves',
        'Creole seasoning (I like Tony Chachere’s Creole Seasoning)',
        'shrimp (optional)',
        'white rice or brown rice',
        'green onions (optional)'],
    instructions: ['Add sausage and chicken to the slow cooker.',
      'Pour chopped bell pepper, celery, garlic, and onion into the slow cooker.',
      'Add diced tomatoes and tomato paste.',
      'Add seasoning, bay leaves, oregano, salt, and pepper.',
      'Pour in chicken stock and stir to combine all ingredients.',
      'Cover and cook on low for 7-8 hours or high for 3-4 hours.',
      'Add the shrimp 30 minutes before finished cooking or until shrimp are cooked through.',
      'While shrimp is cooking prepare rice and add to slow cooker 10 minutes before serving. Stir in rice until combined.',
      'Remove bay leaves and season with salt and pepper to taste.',
      'Serve with chopped parsley or green onions.'],
    ratings: [],
    dietaryRestrictions: ['gluten-free'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 455,
      proteinPercentage: 41,
      carbsPercentage: 52,
      fatPercentage: 7,
    },
    serving: 6,
    time: 120
  },
  {
    id: '16',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/16.jpg',
    description: 'Fried Rice',
    ingredients:
      ['1 cup extra-firm tofu* (8 ounces yields ~1 cup)',
        '1 cup long- or short-grain brown rice* (rinsed thoroughly in a fine mesh strainer)',
        '4 cloves garlic (minced)', '1 cup chopped green onion', '1/2 cup peas', '1/2 cup carrots (finely diced)',
        '3 Tbsp tamari or soy sauce (plus more for veggies + to taste)',
        '1 Tbsp peanut butter', '2-3 Tbsp organic brown sugar, muscovado sugar, or maple syrup',
        '1 clove garlic (minced)', '1-2 tsp chili garlic sauce (more or less depending on preferred spice)',
        '1 tsp toasted sesame oil (optional // or sub peanut or avocado oil)'],
    instructions: ['Preheat oven to 400 degrees F (204 C) and line a baking sheet with parchment paper (or lightly grease with non-stick spray).',
      'In the meantime wrap tofu in a clean, absorbent towel and set something heavy on top (such as a cast iron skillet) to press out the liquid.',
      'Once the oven is preheated, dice tofu into 1/4-inch cubes and arrange on baking sheet. Bake for 26-30 minutes. Youre looking for golden brown edges and a texture thats firm to the touch. The longer it bakes, the firmer and crispier it will become,  tofu remove from the oven around the 26-28 minute mark. I prefer crispy tofu, so I bake mine the full 30 minutes. Set aside.',
      'While the tofu bakes prepare your rice by bringing 12 cups of water to a boil in a large pot. Once boiling, add rinsed rice and stir. Boil on high uncovered for 30 minutes, then strain for 10 seconds and return to pot removed from the heat. Cover with a lid and let steam for 10 minutes*.',
      'While rice and tofu are cooking, prepare sauce by adding all ingredients to a medium-size mixing bowl and whisking to combine. Taste and adjust flavor as needed, adding more tamari or soy sauce for saltiness, peanut butter for creaminess, brown sugar for sweetness, or chili garlic sauce for heat.',
      'Once the tofu is done baking, add directly to the sauce and marinate for 5 minutes, stirring occasionally.',
      'Heat a large metal or cast iron skillet over medium heat. Once hot, use a slotted spoon to scoop the tofu into the pan leaving most of the sauce behind. Cook for 3-4 minutes, stirring occasionally, until deep golden brown on all sides (see photo). Lower heat if browning too quickly. Remove from pan and set aside.',
      'To the still hot pan add garlic, green onion, peas and carrots. Sauté for 3-4 minutes, stirring occasionally, and season with 1 Tbsp (15 ml) tamari or soy sauce (amount as original recipe is written // adjust if altering batch size).',
      'Add cooked rice, tofu, and remaining sauce and stir. Cook over medium-high heat for 3-4 minutes, stirring frequently.',
      'Serve immediately with extra chili garlic sauce or sriracha for heat (optional). Crushed salted, roasted peanuts or cashews make a lovely additional garnish. Leftovers keep well in the refrigerator for 3-4 days, though best when fresh. Reheat in a skillet over medium heat or in the microwave.'],
    ratings: [],
    dietaryRestrictions: ['vegan'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 384,
      proteinPercentage: 33,
      carbsPercentage: 43,
      fatPercentage: 24,
    },
    serving: 4,
    time: 60
  },
  {
    id: '17',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/17.jpg',
    description: 'Spinach Curry',
    ingredients: ['1 13.5oz. can full-fat coconut milk', '8 oz. fresh spinach', '1 yellow onion', '2 cloves garlic',
      '1 Tbsp grated fresh ginger', '2 Tbsp olive oil', '2 tsp ground cumin', '1 tsp garam masala', '1/2 tsp turmeric',
      '1/4 tsp cayenne pepper', '1 large tomato', '1/4 cup water', '3/4 tsp salt (or to taste)'],
    instructions:
      ['Add the coconut milk and spinach to a large pot. Stir and cook over medium heat until the coconut milk is warmed through and has wilted the spinach. Remove from the heat as soon as the spinach has wilted to avoid overcooking the spinach.',
        'Transfer the warm coconut milk and spinach to a blender and pulse until the spinach is in small pieces (you can choose to blend until smooth if you prefer). Set this mixture aside.',
        'Dice the onion, mince the garlic, and grate the ginger. Add the onion, garlic, and ginger to a large skillet along with the olive oil. Sauté over medium heat until the onions are soft (about 5 minutes).',
        'Add the cumin, garam masala, turmeric, and cayenne to the skillet. Stir and cook the spices with the onion, garlic, and ginger for about two minutes more.', 'Dice the tomato and add it to the skillet along with about 1/4 cup water. Stir and cook the tomato with the other ingredients, dissolving any browned bits off the bottom of the skillet, until the tomato has broken down (5-8 minutes).', 'Finally, add the coconut and spinach mixture to the skillet and stir to combine. Allow the mixture to heat through, stirring occasionally.',
        'Taste the creamed spinach and add salt to taste. Start with 1/4 tsp, adding more as needed until the flavors pop (I added 3/4 tsp).'],
    ratings: [],
    dietaryRestrictions: ['vegetarian'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 139,
      proteinPercentage: 33,
      carbsPercentage: 43,
      fatPercentage: 24,
    },
    serving: 4,
    time: 40
  },

  {
    id: '18', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/18.jpg',
    description: 'Quinoa Salad',
    ingredients: [
      '1 cup uncooked quinoa',
      '2 cups gluten-free chicken or vegetable broth',
      '1 cup black beans (from 15-oz can), drained, rinsed',
      '1/2 cup frozen whole kernel corn, thawed',
      '1 small tomato, chopped (1/2 cup)',
      '1/4 cup chopped fresh cilantro',
      '4 medium green onions, chopped (1/4 cup)',
      '1 tablespoon fresh lime juice',
      '1 clove garlic, finely chopped',
      '1/4 teaspoon salt'
    ],
    instructions: [
      '1 Rinse quinoa thoroughly by placing in a fine-mesh strainer and holding under cold running water until water runs clear; drain well.',
      '2 In 2-quart saucepan, heat broth to boiling. Add quinoa; reduce heat to low. Cover; simmer 15 to 20 minutes or until liquid is absorbed.',
      '3 Fluff quinoa with fork. Stir in remaining ingredients. Cook uncovered about 3 minutes, stirring occasionally, until thoroughly heated.'
    ],
    ratings: [],
    dietaryRestrictions: ['gluten-free'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 130,
      proteinPercentage: 23,
      carbsPercentage: 50,
      fatPercentage: 27,
    },
    serving: 2,
    time: 20
  },
  {
    id: '19', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/19.jpg',
    description: 'Spinach Eggs',
    ingredients: ['1 tbsp olive oil',
      '2 onions, halved and thinly sliced (320g)',
      '4 garlic cloves, chopped',
      '1½ tbsp smoked paprika',
      '500g passata',
      '500ml vegetable stock, made with 2 tsp bouillon powder',
      '150g red lentils',
      '400g frozen spinach',
      '400g can borlotti beans',
      '10g basil, chopped',
      '2 tomatoes, cut into wedges',
      '8 eggs'],
    instructions: ['Heat the oil in a large, deep frying pan over a medium heat and fry the onions for 10 mins, stirring occasionally, until softened.',
      'Stir in the garlic and paprika, then the passata and stock.',
      'Add the lentils and spinach.',
      'Bring to the boil, cover, then reduce the heat and simmer for 25-35 mins until the lentils are tender.',
      'Stir in the beans along with the liquid from the can, then add the basil and tomatoes.',
      'Make four gaps in the mixture using a spoon, and crack one egg into each.',
      'Cover and cook over a low heat for 5 mins until the eggs are just set.',
      'Serve half the lentil mixture with the four cooked eggs.',
      'Leave the remaining lentil mixture to cool completely, then keep chilled for up to three days.',
      'To serve, reheat in a smaller pan with a splash of water, then cook the remaining eggs as you did in step two, above.']
    ,
    ratings: [],
    dietaryRestrictions: ['gluten-free'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 476,
      proteinPercentage: 45,
      carbsPercentage: 45,
      fatPercentage: 10,
    },
    serving: 4,
    time: 65
  },
  {
    id: '20', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/20.jpg',
    description: 'Harissa Chicken',
    ingredients: ['4 chicken legs', '4 tbsp harissa paste (rose harissa is nice)', '1 garlic bulb, broken into cloves', '1 lemon, cut into wedges', '400g cherry tomatoes on the vine', '350g new potatoes, halved if large', '50g Kalamata olives, chopped', '2 tbsp olive oil', 'green salad, to serve (optional)'],
    instructions: [
      "Heat oven to 190C/170C fan/gas 5. Score deep lines all over the chicken legs, then rub in the harissa.",
      "Season well and place in a roasting tin. Scatter the garlic over and around the chicken.",
      "Squeeze the lemon wedges over, then place them in the tin with the cherry tomatoes, potatoes and olives.",
      "Season, drizzle over the oil and toss briefly to mix everything together.",
      "Cook in the oven for 45 mins-1 hr until the chicken is cooked through and golden. Serve with salad, if you like."
  ]  ,
    ratings: [],
    dietaryRestrictions: ['gluten-free'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 619,
      proteinPercentage: 27.76,
      carbsPercentage: 11.62,
      fatPercentage: 58.15,
    },
    serving: 4,
    time: 55
  },
  {
    id: '21', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/21.jpg',
    description: 'Spanish Beef Stew',
    ingredients: [
      '1 pound beef stew meat',
      'salt and ground black pepper to taste',
      '½ cup chopped Spanish onion',
      '2 cloves garlic, minced',
      '2 cups chopped red potatoes',
      '1 (14.5 ounce) can diced tomatoes',
      '1 (12 ounce) jar sofrito',
      '½ cup pitted and halved green olives'
    ]
    ,
    instructions: [
      "Heat a large skillet over medium heat. Cook beef in hot skillet until completely browned, about 5 minutes; season with salt and pepper.",
      "Transfer beef to a slow cooker, retaining some of the beef drippings in the skillet.",
      "Return skillet to heat and heat the retained drippings. Saute onion and garlic in hot drippings until softened, about 5 minutes; add to beef in slow cooker.",
      "Stir potatoes, diced tomatoes, sofrito, and olives into the beef mixture.",
      "Cook on Low until beef and potatoes are fork-tender, 4 to 5 hours."
    ]
    ,
    ratings: [],
    dietaryRestrictions: ['gluten-free'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 241,
      proteinPercentage: 33.05,
      carbsPercentage: 23.23,
      fatPercentage: 42.32,
    },
    serving: 6,
    time: 120
  },
  {
    id: '22', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/22a.jpg',
    description: 'Roast vegetables & chickpeas',
    ingredients: ['3 courgettes, thickly sliced',
    '1 aubergine, cut into thick fingers',
    '3 garlic cloves, chopped',
    '2 red peppers, deseeded and chopped into chunks',
    '2 large baking potatoes, peeled and cut into bite-size chunks',
    '1 onion, chopped',
    '1 tbsp coriander seeds',
    '4 tbsp olive oil',
    '400g/14oz can chopped tomatoes',
    '400g/14oz can chickpeas, rinsed and drained',
    'small bunch coriander, roughly chopped'],
    instructions: [
      "Heat oven to 220C/200C fan/gas 7.",
      "Tip all the vegetables into a large roasting tin and toss with the coriander seeds, most of the olive oil and salt and pepper.",
      "Spread everything out to a single layer, then roast for 45 mins, tossing once or twice until the vegetables are roasted and brown round the edges.",
      "Place the tin on a low heat, then add the tomatoes and chickpeas. Bring to a simmer and gently stir.",
      "Season to taste, drizzle with olive oil, then scatter over the coriander. Serve from the tin or pile into a serving dish. Eat with hunks of bread."
    ],
    ratings: [],
    dietaryRestrictions: ['vegan'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 327,
      proteinPercentage: 13.52,
      carbsPercentage: 48.93,
      fatPercentage: 41.55,
    },
    serving: 4,
    time: 60
  },
  {
    id: '23', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/23.jpg',
    description: 'Jambalaya',
    ingredients: [
      "2 tbsp olive oil",
      "1 large onion (180g), finely chopped",
      "4 celery sticks, finely chopped",
      "1 yellow pepper, chopped",
      "2 tsp smoked paprika",
      "½ tsp chilli flakes",
      "½ tsp dried oregano",
      "115g brown basmati rice",
      "400g can chopped tomatoes",
      "2 garlic cloves, finely grated",
      "400g butter beans, drained and rinsed",
      "2 tsp vegetable bouillon powder",
      "large handful of parsley, chopped"
    ]
    ,
    instructions: ['Heat the oil in a large pan set over a high heat and fry the onion, celery and pepper, stirring occasionally, for 5 mins until starting to soften and colour.', 
    'Stir in the spices and rice, then tip in the tomatoes and a can of water. Stir in the garlic, beans and bouillon.', 
    'Bring to a simmer, then cover and cook for 25 mins until the rice is tender and has absorbed most of the liquid.', 
    'Keep an eye on the pan towards the end of the cooking time to make sure it doesn’t boil dry – if it starts to catch, add a little more water.', 
    'Stir in the parsley and serve hot.']
    ,
    ratings: [],
    dietaryRestrictions: ['vegan'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 547,
      proteinPercentage: 13.14,
      carbsPercentage: 56.23,
      fatPercentage: 23.22,
    },
    serving: 2,
    time: 45
  },
  {
    id: '24', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/24.jpg',
    description: 'Mushroom & potato curry',
    ingredients: [
      '1 tbsp oil',
      '1 onion, roughly chopped',
      '1 large potato, chopped into small chunks',
      '1 aubergine, trimmed and chopped into chunks',
      '250g button mushrooms',
      '2-4 tbsp curry paste (depending on how hot you like it)',
      '150ml vegetable stock',
      '400ml can reduced-fat coconut milk',
      'chopped coriander, to serve'
    ]
    ,
    instructions: [
      "Heat the oil in a large saucepan, add the onion and potato.",
      "Cover, then cook over a low heat for 5 mins until the potatoes start to soften.",
      "Throw in the aubergine and mushrooms, then cook for a few more mins.",
      "Stir in the curry paste, pour over the stock and coconut milk.",
      "Bring to the boil, then simmer for 10 mins or until the potato is tender.",
      "Stir through the coriander and serve with rice or naan bre"
    ]
    ,
    ratings: [],
    dietaryRestrictions: ['vegan'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 212,
      proteinPercentage: 9.43,
      carbsPercentage: 28.30,
      fatPercentage: 63.68,
    },
    serving: 4,
    time: 40
  },
  {
    id: '25', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/25.jpg',
    description: 'Courgette Risotto',
    ingredients: ['1 tbsp olive oil', '1 onion and 2 garlic cloves, finely chopped', '3 ripe tomatoes, roughly chopped', '350g carnaroli or other risotto rice', '1 tsp chopped rosemary', '1 ½l hot vegetable stock', '3 courgettes, finely diced', '140g peas, fresh or frozen', 'large handful basil, lightly torn'] ,
    instructions: ['Heat the oil in a large pan. Cook the onion and garlic for 5 mins until the onion has softened.',
    'Add the tomatoes and cook for 3-4 mins until softened and pulpy, then add the rice and rosemary.',
    'Pour in half the stock and leave to cook for 10 mins or until the liquid has evaporated, stirring from time to time.',
    'Add the rest of the stock, then continue to cook for a further 5 mins.',
    'Stir in the courgettes and peas, then cook for another 5 mins or so, stirring until the rice is tender, but the mixture is still a bit saucy.',
    'Can be frozen at this stage for up to 1 month.',
    'Season with plenty of black pepper, then add the basil and stir until wilted. Serve immediately.'],
    ratings: [],
    dietaryRestrictions: ['vegan'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 406,
      proteinPercentage: 13.79,
      carbsPercentage: 80.79,
      fatPercentage: 11.82,
    },
    serving: 4,
    time: 30
  },
  {
    id: '26', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/26.jpg',
    description: 'Lasgna',
    ingredients: [
      '3 red peppers, cut into large chunks',
      '2 aubergines, cut into ½ cm thick slices',
      '8 tbsp olive oil, plus extra for the dish',
      '300g lasagne sheets',
      '125g mozzarella',
      'handful cherry tomatoes, halved',
      'For the tomato sauce',
      '1 tbsp olive oil',
      '2 onions, finely chopped',
      '2 garlic cloves, sliced',
      '1 carrot, roughly chopped',
      '2 tbsp tomato purée',
      '200ml white wine',
      '3 x 400g cans chopped tomatoes',
      '1 bunch of basil, leaves picked',
      'For the white sauce',
      '85g butter',
      '85g plain flour',
      '750ml milk'
  ],
    instructions:[
      "To make the tomato sauce, heat the olive oil in a saucepan. Add the onions, garlic and carrot. Cook for 5-7 mins over a medium heat until softened. Turn up the heat a little and stir in the tomato purée. Cook for 1 min, pour in the white wine, then cook for 5 mins until this has reduced by two-thirds. Pour over the chopped tomatoes and add the basil leaves. Bring to the boil then simmer for 20 mins. Leave to cool then whizz in a food processor. Will keep, cooled, in the fridge for up to three days or frozen for three months.",
      "To make the white sauce, melt the butter in a saucepan, stir in the plain flour, then cook for 2 mins. Slowly whisk in the milk, then bring to the boil, stirring. Turn down the heat, then cook until the sauce starts to thicken and coats the back of a wooden spoon. Will keep, cooled, in the fridge for up to three days or frozen for three months.",
      "Heat the oven to 200C/180C fan/gas 6. Lightly oil two large baking trays and add the peppers and aubergines. Toss with the olive oil, season well, then roast for 25 mins until lightly browned. Reduce the oven to 180C/160C fan/gas 4. Lightly oil a 30 x 20cm ovenproof dish. Arrange a layer of the vegetables on the bottom, then pour over a third of the tomato sauce. Top with a layer of lasagne sheets, then drizzle over a quarter of the white sauce. Repeat until you have three layers of pasta. Spoon the remaining white sauce over the pasta, making sure the whole surface is covered, then scatter over the mozzarella and cherry tomatoes. Bake for 45 mins until bubbling and golden."
    ],
    ratings: [],
    dietaryRestrictions: ['vegetarian'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 461,
      proteinPercentage: 16.65,
      carbsPercentage: 32.15,
      fatPercentage: 51.20,
    },
    serving: 6,
    time: 60
  },
  {
    id: '27', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/27.jpg',
    description: 'Enchiladas',
    ingredients: [
      "1 tsp olive oil",
      "2 onions, chopped",
      "280g carrots, grated",
      "2-3 tsp chilli powder (mild or hot, according to your taste)",
      "2 x 400g cans chopped tomatoes",
      "2 x 400g cans pulses in water, drained (we used mixed beans and lentils)",
      "6 small wholemeal tortillas",
      "200g low-fat natural yogurt",
      "50g extra-mature cheddar cheese (or veg alternative), finely grated"
    ],
    instructions:[
      "Heat the oil in a large frying pan. Cook the onions and carrots for 5-8 mins until soft – add a splash of water if they start to stick. Sprinkle in the chilli powder and cook for 1 min more.",
      "Pour in the tomatoes and pulses and bring to the boil. Turn down the heat and simmer for 5-10 mins, stirring occasionally, until thickened. Remove from the heat and season well.",
      "Heat grill to high. Spread a spoonful of the bean chilli over a large ovenproof dish.",
      "Lay each tortilla onto a board, fill with a few tbsp of chilli mixture, fold over the ends and roll up to seal. Place them into the ovenproof dish. Spoon the remaining chilli on top.",
      "Mix the yogurt and grated cheese together with some seasoning, and spoon over the enchiladas.",
      "Grill for a few mins until the top is golden and bubbling. Serve with a green salad."
    ],
    ratings: [],
    dietaryRestrictions: ['vegetarian'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 21.63,
      proteinPercentage: 33,
      carbsPercentage: 55.81,
      fatPercentage: 27.09,
    },
    serving: 4,
    time: 30
  },
  {
    id: '28', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/28.jpg',
    description: 'Potato & peanut curry',
    ingredients: [
      '1 tbsp coconut oil',
      '1 onion, chopped',
      '2 garlic cloves, grated',
      'thumb-sized piece ginger, grated',
      '3 tbsp Thai red curry paste (check the label to make sure it’s vegetarian/ vegan)',
      '1 tbsp smooth peanut butter',
      '500g sweet potato, peeled and cut into chunks',
      '400ml can coconut milk',
      '200g bag spinach',
      '1 lime, juiced',
      'cooked rice, to serve (optional)',
      'dry roasted peanuts, to serve (optional)'
    ],
    instructions: [
      'Melt 1 tbsp coconut oil in a saucepan over a medium heat and soften 1 chopped onion for 5 mins.',
      'Add 2 grated garlic cloves and a grated thumb-sized piece of ginger, and cook for 1 min until fragrant.',
      'Stir in 3 tbsp Thai red curry paste, 1 tbsp smooth peanut butter and 500g sweet potato, peeled and cut into chunks, then add 400ml coconut milk and 200ml water.',
      'Bring to the boil, turn down the heat and simmer, uncovered, for 25-30 mins or until the sweet potato is soft.',
      'Stir through 200g spinach and the juice of 1 lime, and season well.',
      'Serve with cooked rice, and if you want some crunch, sprinkle over a few dry roasted peanuts.'
    ],
    ratings: [],
    dietaryRestrictions: ['vegetarian'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 387,
      proteinPercentage: 12.74,
      carbsPercentage: 33.02,
      fatPercentage: 54.24,
    },
    serving: 4,
    time: 45
  },
  {
    id: '29', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/29.jpg',
    description: 'Chickpea curry',
    ingredients: [
      "2 tbsp oil",
      "1 onion, diced",
      "1 tsp fresh or dried chilli, to taste",
      "9 garlic cloves (approx 1 small bulb of garlic)",
      "thumb-sized piece ginger, peeled",
      "1 tbsp ground coriander",
      "2 tbsp ground cumin",
      "1 tbsp garam masala",
      "2 tbsp tomato purée",
      "For the curry",
      "2 x 400g cans chickpeas, drained",
      "400g can chopped tomatoes",
      "100g creamed coconut",
      "½ small pack coriander, chopped, plus extra to garnish",
      "100g spinach"
    ],
    instructions: [
      "To make the paste, heat a little of the 2 tbsp oil in a frying pan, add 1 diced onion and 1 tsp fresh or dried chilli, and cook until softened, about 8 mins.",
      "In a food processor, combine 9 garlic cloves, a thumb-sized piece of peeled ginger and the remaining oil, then add 1 tbsp ground coriander, 2 tbsp ground cumin, 1 tbsp garam masala, 2 tbsp tomato purée, ½ tsp salt and the fried onion. Blend to a smooth paste – add a drop of water or more oil, if needed.",
      "Cook the paste in a medium saucepan for 2 mins over a medium-high heat, stirring occasionally so it doesn’t stick.",
      "Tip in two 400g cans drained chickpeas and a 400g can chopped tomatoes, and simmer for 5 mins until reduced down.",
      "Add 100g creamed coconut with a little water, cook for 5 mins more, then add ½ small pack chopped coriander and 100g spinach, and cook until wilted.",
      "Garnish with extra coriander and serve with rice or dhal (or both)."
    ] ,
    ratings: [],
    dietaryRestrictions: ['vegetarian'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 458,
      proteinPercentage: 13.10,
      carbsPercentage: 27.03,
      fatPercentage: 55.02,
    },
    serving: 4,
    time: 25
  },
  {
    id: '30', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/30a.jpg',
    description: 'Coconut & Squash Dhansak',
    ingredients: ['1 tbsp vegetable oil',
    '500g butternut squash (about 1 small squash), peeled and chopped into bite-sized chunks (or buy a pack of ready-prepared to save time), see tip, below left',
    '100g frozen chopped onions',
    '4 heaped tbsp mild curry paste (we used korma)',
    '400g can chopped tomatoes',
    '400g can light coconut milk',
    'mini naan bread, to serve',
    '400g can lentils, drained',
    '200g bag baby spinach',
    '150ml coconut yogurt'],
    instructions: [
      "Heat the oil in a large pan. Put the squash in a bowl with a splash of water.",
      "Cover with cling film and microwave on High for 10 mins or until tender.",
      "Meanwhile, add the onions to the hot oil and cook for a few mins until soft.",
      "Add the curry paste, tomatoes and coconut milk, and simmer for 10 mins until thickened to a rich sauce.",
      "Warm the naan breads in a low oven or in the toaster. Drain any liquid from the squash, then add to the sauce with the lentils, spinach and some seasoning.",
      "Simmer for a further 2-3 mins to wilt the spinach, then stir in the coconut yogurt. Serve with the warm naan and a dollop of extra yogurt."
    ],
    ratings: [],
    dietaryRestrictions: ['vegetarian'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 320,
      proteinPercentage: 11.25,
      carbsPercentage: 36.25,
      fatPercentage: 47.81,
    },
    serving: 4,
    time: 25
  },
  {
    id: '31', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/31.jpg',
    description: 'Chili Garlic Shrimp',
    ingredients: [
      '2 tablespoons chili garlic sauce',
      '2 tablespoons hoisin sauce',
      '1/3 cup shrimp stock (see Cook\'s Note)',
      '1 tablespoon tomato paste',
      '1 tablespoon mirin',
      '1/4 teaspoon sesame oil',
      '2 teaspoons minced fresh ginger',
      '1 clove garlic, minced',
      '2 tablespoons chopped shallot',
      '2 tablespoons chopped cilantro, plus more for garnish',
      '3 tablespoons vegetable oil',
      '1 clove garlic, sliced',
      '1 (1/8-inch-thick) slice fresh ginger',
      '1 pound raw shrimp, 21-25 shrimp per pound, shelled and deveined'
    ],
    instructions: [
      "Combine chili-garlic sauce, hoisin sauce, shrimp stock, tomato paste, mirin, sesame oil, 2 teaspoons minced fresh ginger, 1 clove minced garlic, shallot, and cilantro in a blender or small food processor.",
      "Pulse several times to chop, then purée, 30 to 45 seconds. Set sauce aside, or refrigerate until needed.",
      "Heat oil in a large skillet or wok over medium high heat. When oil is hot, add garlic and ginger slices.",
      "Cook until browned, watching closely to avoid burning, about 2 minutes. Carefully remove garlic and ginger from the oil and discard.",
      "To the seasoned oil, carefully add shrimp and cook until it just begins to turn pink and curl head to tail, about 2 minutes.",
      "Turn shrimp and add prepared sauce. Cook, stirring, until shrimp are bright pink on the outside and the meat is opaque, 2 to 3 minutes. An instant-read thermometer inserted into the center should read 145 degrees F (63 degrees C).",
      "Remove shrimp from the skillet and keep warm. Continue cooking and stirring sauce until thickened and reduced to about 3/4 cup.",
      "Pour thickened sauce over shrimp, and toss to cover."
    ],
    ratings: [],
    dietaryRestrictions: ['non'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 231,
      proteinPercentage: 20.65,
      carbsPercentage: 29.22,
      fatPercentage: 50.54,
    },
    serving: 4,
    time: 25
  },
  {
    id: '32', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/32.jpg',
    description: 'Beef Curry Stew',
    ingredients: [
      "2 pounds cubed beef stew meat",
      "salt and ground black pepper to taste",
      "2 jalapeno peppers, chopped",
      "4 cloves garlic, minced",
      "1 tablespoon minced fresh ginger root",
      "4 tablespoons curry powder",
      "2 cups beef broth",
      "1 (28 ounce) can fire-roasted diced tomatoes",
      "1 pound Yukon Gold potatoes",
      "3 carrots, sliced",
      "1 large onion, sliced"
    ],
    instructions: [
      "Turn on a multi-functional pressure cooker (such as Instant Pot®) and select Saute function.",
      "Pour in olive oil and heat until sizzling; add meat and season with salt and pepper. Cook until browned, 5 to 7 minutes per side.",
      "Transfer meat to a plate, reserving juices in the pot. Add jalapenos, garlic, and ginger to the pot.",
      "Cook and stir until tender, about 2 minutes. Season with curry powder.",
      "Pour 1/2 of the beef broth into the pot; scrape brown bits from the bottom of the pot using a wooden spoon.",
      "Return meat to the pot with remaining beef broth, tomatoes, potatoes, carrots, and onion. Close and lock the lid.",
      "Select high pressure according to manufacturer's instructions and set timer for 35 minutes. Allow 10 to 15 minutes for pressure to build.",
      "Release pressure using the natural-release method according to manufacturer's instructions for 10 minutes.",
      "Release remaining pressure carefully using the quick-release method according to manufacturer's instructions, about 5 minutes more. Unlock and remove the lid."
    ],
    ratings: [],
    dietaryRestrictions: ['non'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 356,
      proteinPercentage: 33,
      carbsPercentage: 43,
      fatPercentage: 24,
    },
    serving: 4,
    time: 85
  },
  // {
  //   id: '33', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/3.jpg',
  //   description: 'Card 3',
  //   ingredients: ['ingredient4', 'ingredient5'],
  //   instructions: ['instru1', 'instru2', 'instru3'],
  //   ratings: [],
  //   dietaryRestrictions: ['vegetarian'],
  //   difficultyLevel: 'advanced',
  //   nutrition: {
  //     totalCalories: 139,
  //     proteinPercentage: 33,
  //     carbsPercentage: 43,
  //     fatPercentage: 24,
  //   },
  //   serving: 4,
  //   time: 40
  // },
  // {
  //   id: '34', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/3.jpg',
  //   description: 'Card 3',
  //   ingredients: ['ingredient4', 'ingredient5'],
  //   instructions: ['instru1', 'instru2', 'instru3'],
  //   ratings: [],
  //   dietaryRestrictions: ['vegetarian'],
  //   difficultyLevel: 'advanced',
  //   nutrition: {
  //     totalCalories: 139,
  //     proteinPercentage: 33,
  //     carbsPercentage: 43,
  //     fatPercentage: 24,
  //   },
  //   serving: 4,
  //   time: 40
  // },



  // { id: '11', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/3.jpg', description: 'Card 3', ingredients: ['ingredient4', 'ingredient5'], instructions: ['instru1', 'instru2', 'instru3'], ratings: [] },
  // { id: '12', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/4.jpg', description: 'Card 2', ingredients: ['ingredient4', 'ingredient5'], instructions: ['instru1', 'instru2', 'instru3'], ratings: [] },
];

