export const data = [
  {
    id: '1', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/1.jpg', description: 'Broccoli stir fry',
    ingredients: ['1/2 pounds (2 large heads) broccoli', '1 head broccolini (or 1 additional head of broccoli)', '1 medium red onion', '1 orange bell pepper', '2 portobello mushroom caps', '3 garlic cloves', '2 teaspoons ginger, grated (about a 2-inch nub)', '2 tablespoons mirin', '2 tablespoons  vinegar', '2 tablespoons soy sauce', '1 teaspoon Sriracha hot sauce', '2 tablespoons sesame oil (regular, not toasted)'],
    instructions: ['Chop the broccoli and broccolini into large florets (about 6 cups florets total). Chop the red onion into bite sized squares. Dice the pepper into bite sized squares', 'Remove the stems from the portobellos (if necessary), slice them into strips, then cut the larger pieces in half. Place all of the vegetables in a large bowl', 'Mince the garlic. Peel the ginger and grate it. Place them together in a small bowl.', 'Stir together the mirin, rice vinegar, soy sauce, and Sriracha in a small bowl.', 'In a large skillet over high heat, and heat the oil. Add the broccoli, broccolini (if using), red onion, bell pepper, and mushrooms and cook 6 to 7 minutes until just starting to brown on edges, stirring occasionally.', 'Add the garlic and ginger cook for 1 minute more, until broccoli is crisp tender but still bright green.', 'Turn off the heat and add the sauce, stirring until combined. Taste and add additional pinches salt as necessary. Serve immediately. Garnish with sesame seeds and green onion (optional).'],
    ratings: [],
    dietaryRestrictions: ['vegetarian'],
    difficultyLevel: 'intermediate',
    nutrition: {
      totalCalories: 370,
      proteinPercentage: 41,
      carbsPercentage: 52,
      fatPercentage: 7,
    },
    serving: 5,
    time: 35
  },
  {
    id: '2', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/2.jpg',
    description: 'Flower Power Eggs',
    ingredients: [' bell pepper', '1 tbsp. vegetable oil', '4 large eggs', 'Chopped parsley, for garnish'],
    instructions: ['Slice bell pepper (or 4 in different colors) horizontally to make four 1/2-inch-thick rings and remove inner white flesh and seeds.', 'In 12-inch nonstick skillet, heat vegetable oil on medium. Cook peppers 2 minutes. Turn peppers over; crack 1 egg into center of each ring. Cook, covered, until eggs have reached desired doneness. Season with 1/4 teaspoon each salt and pepper.', 'To serve, garnish with chopped parsle'],
    ratings: [],
    dietaryRestrictions: ['vegetarian', 'vegan'],
    difficultyLevel: 'beginner',
    nutrition: {
      totalCalories: 220,
      proteinPercentage: 41,
      carbsPercentage: 52,
      fatPercentage: 7,
    },
    serving: 5,
    time: 35
  },
  {
    id: '3',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/3.jpg',
    description: 'Chicken fried rice',
    ingredients: ['2 tablespoons sesame oil',
      '2 tablespoons canola or vegetable oil', '3/4 to 1 pound boneless skinless chicken breasts', 'diced into 1/2-inch pieces', '1/2 cups frozen peas and diced carrots blend ', '3 green onions, trimmed and sliced into thin rounds', ' 2 to 3 garlic cloves, finely minced', '3 large eggs, lightly beaten', '4 cups cooked rice (I use white, long-grain or brown may be substituted. To save time use two 8.8-ounce pouches cooked and ready-to-serve rice)', '3 to 4 tablespoons low-sodium soy sauce',
      'salt and pepper, optional and to taste',],
    instructions: ['To a large non-stick skillet or wok, add the oils, chicken, and cook over medium-high heat for about 3 to 5 minutes, flipping intermittently so all sides cook evenly.', ' Cooking time will vary based on thickness of chicken breasts and sizes of pieces.', 'Remove chicken with a slotted spoon (allow oils and cooking juices from chicken to remain in skillet) and place chicken on a plate; set aside.', 'Add the peas, carrots, green onions, and cook for about 2 minutes, or until vegetables begin to soften, stir intermittently.', 'Add the garlic and cook for 1 minute, stir intermittently.', 'Push vegetables to one side of the skillet, add the eggs to the other side, and cook to scramble, stirring as necessary.'],
    ratings: [],
    dietaryRestrictions: ['non-vegetarian'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 870,
      proteinPercentage: 41,
      carbsPercentage: 52,
      fatPercentage: 7,
    },
    serving: 5,
    time: 35
  },
  {
    id: '4', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/4.jpg',
    description: 'Sushi',
    ingredients: ['6 sheets sushi seaweed aka nori', '1 batch prepared sushi rice', '1/2 lb sashimi-grade raw salmon or desired raw fish of choice', '4 oz cream cheese sliced into strips', '1 avocado sliced', 'soy sauce for serving'],
    instructions: ['Smooth gently with a rice paddle.', 'Layer salmon, cream cheese, and avocado on the rice, and roll it up tightly.', 'Slice with a sharp knife, and enjoy right away with soy sauce.'],
    ratings: [],
    dietaryRestrictions: ['non-vegetarian'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 670,
      proteinPercentage: 41,
      carbsPercentage: 52,
      fatPercentage: 7,
    },
    serving: 5,
    time: 35
  },
  {
    id: '5',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/5.jpg',
    description: 'Chicken Parmesan',
    ingredients: ['3 boneless skinless chicken breasts, cut in half horizontally to make 6 breast halves*', '½ cup freshly grated parmesan cheese, divided', '2 eggs', '1 cup panko bread crumbs', '1 cup Italian style bread crumbs, or panko', '1 teaspoon garlic powder', '3 Tablespoons oil', '24 ounces marinara sauce, or HOMEMADE', '1 cup shredded mozzarella cheese', 'fresh basil leaves, for serving'],
    instructions: ['Preheat oven to 450 degrees F.',
      'Butterfly chicken breasts: Place one hand on top of the breast and carefully run a knife through the center of the meat to create two, even, thin breast halves.',
      'Pat chicken dry and season well on both sides with salt and pepper.',
      'Add eggs to a shallow bowl and beat well. Add breadcrumbs, parmesan and garlic powder to another shallow bowl and stir to combine.',
      'Dip each piece of chicken into the egg mixture, and then press into breadcrumbs, coating on both sides.',
      'Add oil to a large skillet over medium-high heat. Once hot, add breaded chicken and cook for about 2 minutes on each side, until golden, but not cooked through.',
      ' to cover the bottom of the pan. Place breaded chicken on top.',
      'Add a spoonful of marinara sauce over the chicken, followed by a sprinkle of mozzarella and parmesan cheese.',
      'Bake for 10-15 minutes or until cheese is melted and bubbly and chicken is cooked through (165 degrees F).',
      'Garnish with fresh chopped basil. Serve over hot cooked spaghetti noodles, with extra sauce, if desired.'],
    ratings: [],
    dietaryRestrictions: ['non-vegetarian'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 378,
      proteinPercentage: 41,
      carbsPercentage: 52,
      fatPercentage: 7,
    },
    serving: 6,
    time: 35
  },

  {
    id: '6',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/6.jpg',
    description: 'Taco salad',
    ingredients: ['1 pound lean ground beef',
      '1 (16 ounce) can chili beans',
      '1 (16 ounce) bottle French dressing',
      '1 (1.25 ounce) package taco seasoning mix',
      '1 (14.5 ounce) package tortilla chips',
      '1 head iceberg lettuce, shredded',
      '2 cups shredded Cheddar cheese',
      '1 cup chopped tomatoes',
      '½ cup prepared salsa',
      '4 tablespoons sour cream'],
    instructions:
      ['Heat a large skillet over medium-high heat.',
        'Cook and stir ground beef in the hot skillet until browned and crumbly, 5 to 7 minutes.',
        'Drain and discard grease. Stir in chili beans, French-style dressing, and seasoning mix.',
        'Fill the empty dressing bottle 2/3 full of water and add to the skillet.',
        'Bring to a boil, reduce heat, and simmer for 15 minutes.',
        'Crush the bag of chips, open the bag, and toss crushed chips into a large bowl. Add lettuce, cheese, and tomatoes.',
        'Pour meat mixture into the bowl; mix well. Top with salsa and sour cream.'],
    ratings: [],
    dietaryRestrictions: ['non-vegetarian'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 846,
      proteinPercentage: 24.42,
      carbsPercentage: 21.19,
      fatPercentage: 54.89,
    },
    serving: 8,
    time: 35
  },
  {
    id: '7',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/7a.jpg',
    description: 'Grilled Shrimp',
    ingredients:
      ['1 large clove garlic',
        '1 teaspoon coarse salt',
        '1 teaspoon paprika',
        '½ teaspoon cayenne pepper',
        '2 tablespoons olive oil',
        '2 teaspoons lemon juice',
        '2 pounds large shrimp, peeled and deveined',
        '8 wedges lemon, for garnish'],
    instructions: ['Preheat a grill for medium heat.',
      'Crush garlic and salt together in a small bowl with a fork. Mix in paprika and cayenne. Stir in olive oil and lemon juice to form a paste.',
      'Combine garlic paste and shrimp in a large bowl and toss until shrimp are evenly coated.',
      'Lightly oil the grill grate. Grill shrimp until opaque, 2 to 3 minutes.'],
    ratings: [],
    dietaryRestrictions: ['non-vegetarian'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 164,
      proteinPercentage: 60.98,
      carbsPercentage: 13.29,
      fatPercentage: 25.73,
    },
    serving: 6,
    time: 25
  },
  {
    id: '8',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/8.jpg',
    description: 'Creamy Pasta',
    ingredients: ['1 tablespoon panko bread crumbs',
      '1 tablespoon hemp seeds',
      '1/3 teaspoon sea salt',
      'extra-virgin olive oil to taste, for drizzling',
      '1/4 cup chopped fresh herbs (chives, tarragon, or parsley)',
      '10 ounces shell pasta',
      '1 tablespoon extra-virgin olive oil',
      '3 cups Brussels sprouts, halved',
      '2 tablespoons white wine (or water)',
      '2 scallions, sliced',
      'sea salt and freshly ground black pepper to taste',
      '1 cup Almond Breeze Unsweetened Original Almondmilk or Almond Breeze Extra Creamy Almondmilk',
      '1 cup raw slivered almonds',
      '2 tablespoons white miso paste',
      '2 garlic cloves',
      '1/2 teaspoon Dijon mustard',
      '1/4 cup freshly squeezed lemon juice',
      '2 tablespoons extra-virgin olive oil',
      '1/2 teaspoon sea salt'],
    instructions:
      ['Preheat the oven to 400 degrees F (200 degrees c) and brush a 7x9 baking dish with olive oil.',
        'Make the White Miso Sauce: In a high-speed blender, puree the cashews, miso paste, garlic, Dijon mustard, water, lemon juice, olive oil, and salt until smooth.',
        'Make the pasta: Bring a large pot of salted water to a boil. Prepare the pasta according to the instructions on the package, cooking until al dente. Drain and toss with a little olive oil so that it doesn’t get clumpy.',
        'Heat 1 tablespoon olive oil in a medium skillet over medium-high heat. Add Brussels sprouts and cook, stirring occasionally until browned and beginning to soften, 5 to 7 minutes. Remove from heat, pour in white wine (or water). Stir to scrape up any bits that have stuck to the bottom of the pan.',
        'Add pasta, scallions, and white miso sauce. Stir to coat, then transfer to the baking dish. Top with panko bread crumbs, hemp seeds, a few pinches of salt, and drizzle the top with olive oil.',
        'Bake, covered, until the Brussels sprouts are fully tender and the dish is warmed through, about 15 minutes.',
        'Remove from the oven, top with fresh herbs and serve.'],
    ratings: [],
    dietaryRestrictions: ['vegan'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 385,
      proteinPercentage: 72.73,
      carbsPercentage: 8.31,
      fatPercentage: 21.95,
    },
    serving: 5,
    time: 45
  },
  {
    id: '9',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/9.jpg',
    description: 'Sushi',
    ingredients: ['1 ½ cups uncooked short-grain white rice',
      '1 ½ cups water',
      '⅓ cup red wine vinegar',
      '2 teaspoons white sugar',
      '1 teaspoon salt',
      '½ avocado - peeled, pitted, and thinly sliced',
      '1 teaspoon lemon juice',
      '¼ cup sesame seeds, or as needed',
      '½ cucumber - peeled, seeded, and cut into matchsticks',
      '½ green bell pepper, seeded and cut into matchsticks',
      '½ zucchini, cut into matchsticks'],
    instructions:
      ['Place rice and water in a saucepan over high heat, bring to a boil, and reduce heat to very low.',
        'Cover with a tight-fitting lid and simmer rice until water is absorbed, about 15 minutes. Remove rice from heat and allow to stand covered for 10 minutes.',
        'Mix red wine vinegar, sugar, and salt in a bowl until sugar has dissolved. Fluff rice with a fork and transfer into a large bowl; pour vinegar mixture into the rice and stir to coat rice.',
        'Spread rice out onto a large piece of parchment paper and fan the rice until cool. Cover rice with damp paper towels.',
        'Sprinkle avocado slices with lemon juice in a bowl.',
        'Spread a thin layer of sesame seeds onto a sushi mat. Pick up about half a cup of cooled rice and place onto sushi mat in an even layer. Place 1/4 of the cucumber, avocado slices, bell pepper, and zucchini in a line down the middle of the rice.',
        'Pick up the edge of the sushi mat, fold the bottom edge of the sheet up, enclosing the filling, and tightly roll the sushi into a thick cylinder.',
        'Once the sushi is rolled, wrap it in the mat and gently squeeze to compact it tightly.',
        'Repeat with remaining ingredients to make 4 rolls. Place rolls on a serving plate, slice into 6 or 8 pieces per roll, and cover with damp paper towels until serving time.'],
    ratings: [],
    dietaryRestrictions: ['vegetarian'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 670,
      proteinPercentage: 41,
      carbsPercentage: 52,
      fatPercentage: 7,
    },
    serving: 4,
    time: 55
  },
  {
    id: '10',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/10.jpg',
    description: 'Roasted Chicken',
    ingredients:
      ['2 pounds red potatoes (about 6 medium), cut into 3/4-inch pieces',
        '1 large onion, coarsely chopped',
        '2 tablespoons olive oil',
        '3 garlic cloves, minced',
        '1-1/4 teaspoons salt, divided',
        '1 tablespoon minced fresh rosemary or 1 teaspoon dried rosemary, crushed, divided',
        '3/4 teaspoon pepper, divided',
        '1/2 teaspoon paprika',
        '6 bone-in chicken thighs (about 2-1/4 pounds), skin removed',
        '6 cups fresh baby spinach (about 6 ounces)',
        'Lemon wedges, optional'],
    instructions: ['Preheat oven to 425°. In a large bowl, combine potatoes, onion, oil, garlic, 3/4 teaspoon salt, 2 teaspoons fresh rosemary or 1/2 teaspoon dried rosemary, and 1/2 teaspoon pepper; toss to coat.',
      'Transfer to a 15x10x1-in. baking pan coated with cooking spray.',
      'In a small bowl, mix paprika and the remaining salt, rosemary, and pepper. Sprinkle chicken with paprika mixture; arrange over vegetables.',
      'Roast until a thermometer inserted in chicken reads 170°-175° and vegetables are just tender, 35-40 minutes.',
      'Remove chicken to a serving platter; keep warm.',
      'Top vegetables with spinach.',
      'Roast until vegetables are tender and spinach is wilted, 8-10 minutes longer.',
      'Stir vegetables to combine; serve with chicken. If desired, serve with additional fresh rosemary and lemon wedges.'],
    ratings: [],
    dietaryRestrictions: ['gluten-free'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 357,
      proteinPercentage: 41,
      carbsPercentage: 52,
      fatPercentage: 7,
    },
    serving: 3,
    time: 35
  },

  {
    id: '12',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/12.jpg',
    description: ' Korma',
    ingredients:
      ['1 red onion, quartered, divided',
        '1 green  chile pepper, stemmed',
        '½ cup water, divided',
        '¼ cup raw cashews',
        '2 cloves garlic',
        '2 tablespoons tomato paste',
        '1 (1 inch) piece fresh ginger',
        '5 whole cloves',
        '3 green cardamom pods',
        '1 black cardamom pod',
        '1 bay leaf',
        '1 teaspoon cumin seeds',
        '¼ teaspoon whole black peppercorns',
        '¼ teaspoon ground coriander',
        '¼ inch cinnamon stick',
        '¼ cup light vegetable oil',
        '8 ¾ ounces cauliflower, cut into large pieces',
        '5 ¼ ounces broccoli, cut into large pieces',
        '2 tomatoes, cut into large chunks',
        '1 cup canned chickpeas (garbanzo beans), drained with liquid reserved',
        '1 carrot, sliced',
        '1 red eye chile pepper, chopped',
        '½ tablespoon garam masala',
        '½ teaspoon ground turmeric',
        '¼ teaspoon chili powder',
        '1 cup baby spinach leaves',
        '1 cup full-fat coconut milk',
        '½ cup vegan yogurt',
        '2 ounces roasted cashews, chopped',
        '½ cup chopped fresh cilantro'],
    instructions: ['Blend 1/4 of the onion, green chile pepper, 1/4 cup water, cashews, garlic, tomato paste, and ginger together in an electric blender, adding extra water if necessary, until paste is creamy and has the consistency of a pesto. Set aside.',
      'Combine cloves, green and black cardamom pods, bay leaf, cumin seeds, peppercorns, coriander, and cinnamon in a mortar. Smash using a pestle to break open spices slightly, 3 to 4 times. Thinly slice remaining onion quarters.',
      'Turn on a multi-functional pressure cooker (such as Instant Pot®) and select Saute function. Add smashed spice mixture and toast until fragrant, about 30 seconds. Pour in oil followed by cashew pesto, onion slices, cauliflower, broccoli, tomatoes, chickpeas, carrot, red chile pepper, garam masala, turmeric, and chili powder. Stir. Cancel the Saute function. Close and lock the lid.',
      'Select high pressure according to manufacturers instructions; set timer for 5 minutes. Allow 10 minutes for pressure to build.',
      'Release pressure using the natural-release method according to manufacturers instructions, 10 to 40 minutes. Unlock and remove the lid. Stir in spinach and mix to help wilt. Stir in coconut milk and yogurt. Mix and serve with roasted cashews and cilantro on top.'],
    ratings: [],
    dietaryRestrictions: ['gluten-free'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 544,
      proteinPercentage: 32.85,
      carbsPercentage: 9.56,
      fatPercentage: 64.34,
    },
    serving: 4,
    time: 55
  },
  {
    id: '13',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/13.jpg',
    description: ' Greek Couscous Salad',
    ingredients:
      ['½ cup water',
        '¼ cup chicken broth',
        '1 teaspoon minced garlic',
        '½ cup pearl (Israeli) couscous',
        '1 cup canned chickpeas (garbanzo beans), rinsed and drained',
        '¼ cup chopped sun-dried tomatoes',
        '¼ cup sliced Kalamata olives',
        '2 tablespoons crumbled feta cheese',
        '1 tablespoon white wine vinegar',
        '1 ½ teaspoons lemon juice',
        '1 teaspoon dried oregano',
        '½ teaspoon ground black pepper'],
    instructions: ['Pour water and chicken broth into a saucepan; stir in the garlic and bring to a boil. Stir in pearl couscous, cover the pan, and remove from heat. Allow couscous to stand until water has been absorbed, about 5 minutes; fluff with a fork. Allow couscous to cool to warm temperature.',
      'Lightly toss couscous, chickpeas, sun-dried tomatoes, olives, and feta cheese in a large serving bowl.',
      'To make the dressing: Mix white wine vinegar, lemon juice, oregano, and black pepper in a small bowl until well combined. Pour over couscous mixture; toss again to serve.'],
    ratings: [],
    dietaryRestrictions: ['vegetarian'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 254,
      proteinPercentage: 14.17,
      carbsPercentage: 66.14,
      fatPercentage: 21.26,
    },
    serving: 3,
    time: 45
  },
  {
    id: '14',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/14.jpg',
    description: ' Bibimbap',
    ingredients:
      ['1 English cucumber, cut into matchsticks',
        '¼ cup gochujang (Korean hot pepper paste) (Optional)',
        '1 bunch fresh spinach, cut into thin strips',
        '1 tablespoon soy sauce',
        '2 teaspoons olive oil, divided',
        '2 carrots, cut into matchsticks',
        '1 clove garlic, minced',
        '1 pinch red pepper flakes',
        '1 pound thinly-sliced beef top round steak',
        '4 large eggs',
        '4 cups cooked white rice',
        '4 teaspoons toasted sesame oil, divided',
        '1 teaspoon sesame seeds',
        '2 teaspoons gochujang (Korean hot pepper paste), divided (Optional)'],
    instructions: ['Stir together cucumber pieces and gochujang paste in a bowl; set aside.',
      'Bring about 2 cups water to a boil in a large nonstick skillet and stir in spinach; cook until bright green and wilted, 2 to 3 minutes.',
      'Drain spinach and squeeze out as much moisture as possible; set spinach aside in a bowl and stir in soy sauce.',
      'Heat 1 teaspoon olive oil in a large nonstick skillet; cook and stir carrots until softened, about 3 minutes.',
      'Stir in garlic and cook just until fragrant, about 1 minute. Stir in cucumber mixture; sprinkle with red pepper flakes. Set carrot mixture aside in a bowl.',
      'Brown beef in a clean nonstick skillet over medium heat, about 5 minutes per side; set aside.',
      'Heat remaining 1 teaspoon olive oil in another nonstick skillet over medium-low heat.',
      'Fry eggs just on one side until yolks are runny, but whites are firm, 2 to 4 minutes.',
      'Divide cooked rice into 4 large serving bowls; top with spinach mixture, a few pieces of beef, and cucumber mixture. Place 1 egg atop each serving.',
      'Drizzle each bowl with 1 teaspoon sesame oil, a sprinkle of sesame seeds, and a small amount of gochujang paste if desired.'],
    ratings: [],
    dietaryRestrictions: ['non-vegetarian'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 569,
      proteinPercentage: 24.69,
      carbsPercentage: 44.18,
      fatPercentage: 30.13,
    },
    serving: 4,
    time: 35
  },
  {
    id: '11',
    imageSource: 'https://storage.googleapis.com/makeiteasyrp808/11a.jpg',
    description: ' Jambalaya',
    ingredients:
      ['boneless chicken breasts and/or thighs',
        'andouille sausage',
        'tomato paste',
        'white onion',
        'celery',
        'green bell pepper',
        'garlic',
        'chicken broth',
        'diced tomatoes',
        'dried oregano',
        'bay leaves',
        'Creole seasoning (I like Tony Chachere’s Creole Seasoning)',
        'shrimp (optional)',
        'white rice or brown rice',
        'green onions (optional)'],
    instructions: ['Add sausage and chicken to the slow cooker.',
      'Pour chopped bell pepper, celery, garlic, and onion into the slow cooker.',
      'Add diced tomatoes and tomato paste.',
      'Add seasoning, bay leaves, oregano, salt, and pepper.',
      'Pour in chicken stock and stir to combine all ingredients.',
      'Cover and cook on low for 7-8 hours or high for 3-4 hours.',
      'Add the shrimp 30 minutes before finished cooking or until shrimp are cooked through.',
      'While shrimp is cooking prepare rice and add to slow cooker 10 minutes before serving. Stir in rice until combined.',
      'Remove bay leaves and season with salt and pepper to taste.',
      'Serve with chopped parsley or green onions.'],
    ratings: [],
    dietaryRestrictions: ['gluten-free'],
    difficultyLevel: 'advanced',
    nutrition: {
      totalCalories: 357,
      proteinPercentage: 41,
      carbsPercentage: 52,
      fatPercentage: 7,
    },
    serving: 6,
    time: 120
  },

  // { id: '11', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/3.jpg', description: 'Card 3', ingredients: ['ingredient4', 'ingredient5'], instructions: ['instru1', 'instru2', 'instru3'], ratings: [] },
  // { id: '12', imageSource: 'https://storage.googleapis.com/makeiteasyrp808/4.jpg', description: 'Card 2', ingredients: ['ingredient4', 'ingredient5'], instructions: ['instru1', 'instru2', 'instru3'], ratings: [] },
];

